/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-26 at 23:35:33 UTC 
 * Modify at your own risk.
 */

package com.arshu.roommate.server.endpoint.rmendpoint.model;

/**
 * Model definition for JoinRoomRequest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the rmendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class JoinRoomRequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> mateList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Room room;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getMateList() {
    return mateList;
  }

  /**
   * @param mateList mateList or {@code null} for none
   */
  public JoinRoomRequest setMateList(java.util.List<java.lang.Long> mateList) {
    this.mateList = mateList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Room getRoom() {
    return room;
  }

  /**
   * @param room room or {@code null} for none
   */
  public JoinRoomRequest setRoom(Room room) {
    this.room = room;
    return this;
  }

  @Override
  public JoinRoomRequest set(String fieldName, Object value) {
    return (JoinRoomRequest) super.set(fieldName, value);
  }

  @Override
  public JoinRoomRequest clone() {
    return (JoinRoomRequest) super.clone();
  }

}
